### ISSUE TITLE
Speed of distance matrix column computation

### ISSUE THREAD

**Issue by SebKrantz** [fsavje/distances#7]
Hi, I like the idea of the package. However it appears to me that some of the math underlying the distance_columns function is not optimal. For my specific application I thus created a simple C function to compute the euclidian distance of a vector, which is about 5x faster than `distance_columns()`. If the performance could be improved, potentially even to allow multithreading over columns bring computed, this would become very useful. 

``` r
library(inline)
## Use of .Call convention with C code
dist_vec <- cfunction(signature(mat = "numeric", vec = "numeric"), 
                      "
    int ncol = length(vec), l = length(mat) / ncol;
    SEXP res = PROTECT(allocVector(REALSXP, l));
    double *pm = REAL(mat), *pv = REAL(vec), *pres = REAL(res);
    memset(pres, 0, sizeof(double) * l);
    
    for (int j = 0; j < ncol; ++j) {
      double *pmj = pm + j * l, v = pv[j], tmp;
      for (int i = 0; i < l; ++i) {
        tmp = pmj[i] - v;
        pres[i] += tmp * tmp;
      }
    }
    
    for (int i = 0; i < l; ++i) {
      pres[i] = sqrt(pres[i]);
    }
    UNPROTECT(1);
    return res;   
    ", 
   language = "C", # verbose = TRUE
)

library(distances)
# Matrix 100k rows, 100 columns
mat <- matrix(rnorm(1e7, 10), ncol = 100)
dist_mat <- distances(mat)

# Check
all.equal(`attributes<-`(distance_columns(dist_mat, 1L), NULL), dist_vec(mat, mat[1L, ]))
#> [1] TRUE

# Benchmark
library(microbenchmark)
microbenchmark(distance_columns(dist_mat, 1L), dist_vec(mat, mat[1L, ]))
#> Warning in microbenchmark(distance_columns(dist_mat, 1L), dist_vec(mat, : less
#> accurate nanosecond times to avoid potential integer overflows
#> Unit: milliseconds
#>                            expr       min        lq     mean    median
#>  distance_columns(dist_mat, 1L) 19.628094 19.814870 20.13231 19.892749
#>        dist_vec(mat, mat[1L, ])  3.731533  3.798793  3.89051  3.825177
#>         uq       max neval
#>  20.042583 28.363718   100
#>   3.860294  6.518016   100
```

<sup>Created on 2022-12-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by fsavje** [comment]
Dear Sebastian,

The point of the `distance` package is to allow for quick "random access" to distance matrices, and quick nearest neighbor search. This is done using a BD-tree data structure (through a wrapper of the [ANN library](http://www.cs.umd.edu/~mount/ANN/)). This means that there is a high initialization cost, but a low query cost. The search object also requires low memory. The `distance_columns()` function is not the main functionality of the package.

If you want to calculate complete columns or the complete matrix, the `distance` package isn't for you. As you note, a naive implementation that just sequentially derive the distances will better. For your setting, the `dist()` function in base R is probably the way to go.

**Comment by SebKrantz** [comment]
Ok, thanks for the explanation. `dist()` does not work because due to memory constraints I indeed need to access one column at a time. Of course random access to arbitrary elements of the matrix is nice, but I presume accessing full columns is more commom as it is easy to produce a distance matrix that does not fit in memory, and a more efficient solution than `sqrt(rowSums((tmat - vec)^2))` seems not to exist in R so far. Anyway, if your not interested in adding this I might add it to *collapse*.

**Comment by fsavje** [comment]
Dear Sebastian,

I'm happy to update `distance_columns()` with improvements, and I very much appreciate your suggestions! However, the code you provided has more limited functionality than `distance_columns()`. It does not do any input checking, it can only derive one column at a time, and it cannot return subsets of the rows. Furthermore, as far as I understand your suggestion provides only a constant-factor run time improvement over the existing code. My time is limited at the moment and I don't find this sufficiently urgent, so I won't be able to adapt your code snippet to production-level code. If you have the time and energy to do it yourself, please make a pull request and I'll review it. But I understand if you prefer to add it to your own package instead. Nevertheless, I appreciate you reaching out with the suggestion.

**Comment by SebKrantz** [comment]
FYI, I created `fdist()` now In collapse (https://github.com/SebKrantz/collapse/blob/master/src/programming.c#L848). Speed: `fdist(mat)` is 4x faster than `dist(mat)`, `fdist(mat, vec)` is 20x faster than `sqrt(colSums((t(mat) - vec)^2))`, and `fdist(x, y)` is 3x faster than `sqrt(sum((x-y)^2))`. Multithreading allows further performance gains.

**Comment by fsavje** [comment]
Awesome! Thanks for sharing.
